### ISSUE TITLE
Add a better README File

### ISSUE THREAD

**Issue by Catlow1989** [Catlow1989/Treehouse#1]
## TODO

_No README file created, important to allow other what is in, and how to use the Repo._
- [ ] This is a list using Mark Down
- [ ] Add a new README
- [ ] Ensure READMDE explains what is in the repo

:tada: :ok:
